import matplotlib.pyplot as plt
import logging

logger = logging.getLogger("TimeSeriesForecaster")


def plot_forecast(series, forecast, horizon):
    """
    Plot the original time series along with the forecasted values.

    The plot displays:
    - the historical series (blue)
    - the predicted future values based on ARIMA + GARCH (red)

    Parameters
    ----------
    series : pandas.Series
        Historical time series indexed by date.
    forecast : array-like
        Forecasted numerical values generated by ARIMA.
    horizon : int
        Number of forecasted points to display.

    Returns
    -------
    None
        Displays a Matplotlib figure.

    Notes
    -----
    Logging Levels:
        - INFO: indicates that the forecast plot is being displayed
        - DEBUG: confirms the plot display completion

    Examples
    --------
    >>> plot_forecast(series, forecast, 20)
    Displays the forecast figure in a Matplotlib window.
    """
    logger.info("Displaying forecast plot")

    plt.figure(figsize=(10, 5))
    plt.plot(series, label="Original")
    plt.plot(range(len(series), len(series) + horizon), forecast, label="Forecast", color="red")
    plt.legend()
    plt.title("ARIMA + GARCH Forecast")
    plt.show()

    logger.debug("Forecast plot displayed")
